# Generated by Django 4.2 on 2023-12-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationstationdistance',
            name='station_distance',
            field=models.DecimalField(decimal_places=16, max_digits=30),
        ),
        migrations.AlterField(
            model_name='stationstationdistance',
            name='station_distance_units',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
