# Generated by Django 4.2 on 2024-03-03 20:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReducedFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=15, unique=True)),
                ('reduced_feature_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
            options={
                'db_table': 'reduced_features',
            },
        ),
        # migrations.AddField(
        #     model_name='propertydata',
        #     name='reduced_features',
        #     field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.reducedfeatures'),
        # ),
    ]
