# Generated by Django 4.2.7 on 2023-11-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateagent',
            name='accreditations',
            field=models.ManyToManyField(through='backend.EstateAgentAccreditation', to='backend.accreditation'),
        ),
    ]
