# Generated by Django 4.2 on 2024-03-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reducedfeatures',
            table='reduced_features',
        ),
    ]
