# Generated by Django 4.2 on 2023-12-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_stationstationdistance_station_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplanproperty',
            name='floorplan_caption',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imageproperty',
            name='image_caption',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
