# Generated by Django 4.2.7 on 2023-11-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_estateagent_accreditations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='gone',
            new_name='un_published',
        ),
        migrations.RemoveField(
            model_name='property',
            name='removed_by_lister',
        ),
        migrations.AlterField(
            model_name='ownershipretirement',
            name='ownership_type',
            field=models.BooleanField(null=True),
        ),
    ]
