# Generated by Django 4.2 on 2023-12-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_text_description_alter_text_disclaimer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettinginfo',
            name='let_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
