# Generated by Django 4.2.7 on 2023-11-18 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_gone_property_un_published_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Floorplan',
            new_name='Floorplans',
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='Statuses',
        ),
        migrations.AddField(
            model_name='estateagent',
            name='branch_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='broadband',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadband', to='backend.location'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='epc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epc', to='backend.location'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='floorplans',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='floorplans', to='backend.floorplans'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='key_features',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='key_features', to='backend.keyfeature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='layout',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='backend.location'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='listing_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_type', to='backend.location'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='backend.location'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='ownership',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='backend.location'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='prices',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='backend.prices'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='statuses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='backend.statuses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='tax',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax', to='backend.location'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='tenure',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenure', to='backend.location'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='views',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='views_id', to='backend.views'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=20)),
                ('room', models.IntegerField(null=True)),
                ('room_name', models.CharField(max_length=255, null=True)),
                ('room_description', models.TextField(null=True)),
                ('room_width', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('room_length', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('room_unit', models.CharField(max_length=10, null=True)),
            ],
            options={
                'unique_together': {('property_id', 'room')},
            },
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='rooms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='backend.rooms'),
            preserve_default=False,
        ),
    ]
