# Generated by Django 4.2.7 on 2023-11-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_floorplan_floorplans_rename_image_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('property_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('listing_type', models.CharField(max_length=30)),
                ('letting_type', models.CharField(max_length=50)),
            ],
        ),
    ]
