# Generated by Django 4.2 on 2023-12-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_affiliation_affiliation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateagent',
            name='agent_description',
            field=models.TextField(),
        ),
    ]
