# Generated by Django 4.2 on 2023-12-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_estateagent_agent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydata',
            name='furnished',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertydata',
            name='property_sub_type',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='propertydata',
            name='property_type',
            field=models.CharField(max_length=35),
        ),
    ]
