# Generated by Django 4.2.7 on 2023-11-19 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_listingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvalue',
            name='broadband',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadband_id', to='backend.broadband'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='epc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epc_id', to='backend.epc'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='floorplans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorplans_id', to='backend.floorplans'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_id', to='backend.images'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='key_features',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_features_id', to='backend.keyfeature'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='layout',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layout_id', to='backend.layout'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='listing_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_type_id', to='backend.listingtype'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_id', to='backend.location'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='ownership',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownership_id', to='backend.ownershipretirement'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='prices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_id', to='backend.prices'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_id', to='backend.rooms'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='statuses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses_id', to='backend.statuses'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='tax',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_id', to='backend.tax'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='tenure',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenure_id', to='backend.tenure'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='text_elements',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_elements_id', to='backend.textelements'),
        ),
    ]
