# Generated by Django 4.2.7 on 2023-11-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_propertyvalue_broadband_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtype',
            name='letting_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listingtype',
            name='listing_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
