# Generated by Django 4.2.7 on 2023-11-19 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_listingtype_letting_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keyfeature',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prices',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rooms',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='statuses',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='views',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='propertyvalue',
            name='floorplans',
        ),
        migrations.RemoveField(
            model_name='propertyvalue',
            name='images',
        ),
        migrations.RemoveField(
            model_name='propertyvalue',
            name='key_features',
        ),
        migrations.RemoveField(
            model_name='propertyvalue',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='propertyvalue',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='propertyvalue',
            name='statuses',
        ),
        migrations.RemoveField(
            model_name='propertyvalue',
            name='views',
        ),
        migrations.AddField(
            model_name='keyfeature',
            name='keyFeature_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='keyFe', to='backend.propertyvalue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prices',
            name='prices_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='backend.propertyvalue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='rooms_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='backend.propertyvalue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statuses',
            name='statuses_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statu', to='backend.propertyvalue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='views',
            name='views_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='backend.propertyvalue'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='keyfeature',
            unique_together={('keyFeature_id', 'key_feature')},
        ),
        migrations.AlterUniqueTogether(
            name='prices',
            unique_together={('prices_id', 'price')},
        ),
        migrations.AlterUniqueTogether(
            name='rooms',
            unique_together={('rooms_id', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='statuses',
            unique_together={('statuses_id', 'status', 'status_date')},
        ),
        migrations.AlterUniqueTogether(
            name='views',
            unique_together={('views_id', 'view_date')},
        ),
        migrations.RemoveField(
            model_name='keyfeature',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='statuses',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='views',
            name='property_id',
        ),
    ]
