# Generated by Django 4.2 on 2023-12-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_room_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='epc',
            name='epc_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='image_scraped',
            field=models.BooleanField(default=False),
        ),
    ]
