# Generated by Django 4.2 on 2023-12-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_epc_epc_scraped_image_image_scraped'),
    ]

    operations = [
        migrations.AddField(
            model_name='epc',
            name='ei_image',
            field=models.ImageField(null=True, upload_to='ei_image/'),
        ),
        migrations.AddField(
            model_name='epc',
            name='epc_image',
            field=models.ImageField(null=True, upload_to='epc_image/'),
        ),
    ]
