# Generated by Django 4.2.7 on 2023-11-19 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_keyfeature_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyfeature',
            old_name='keyFeature_id',
            new_name='key_feature_id',
        ),
        migrations.AlterUniqueTogether(
            name='keyfeature',
            unique_together={('key_feature_id', 'key_feature')},
        ),
    ]
