# Generated by Django 4.2.7 on 2023-11-19 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_keyfeature_id_keyfeature_key_feature_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prices',
            old_name='prices_id',
            new_name='price_id',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='rooms_id',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='statuses',
            old_name='statuses_id',
            new_name='status_id',
        ),
        migrations.RenameField(
            model_name='views',
            old_name='views_id',
            new_name='view_id',
        ),
        migrations.AlterUniqueTogether(
            name='prices',
            unique_together={('price_id', 'price')},
        ),
        migrations.AlterUniqueTogether(
            name='rooms',
            unique_together={('room_id', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='statuses',
            unique_together={('status_id', 'status', 'status_date')},
        ),
        migrations.AlterUniqueTogether(
            name='views',
            unique_together={('view_id', 'view_date')},
        ),
    ]
