# Generated by Django 4.2 on 2024-01-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_epc_ei_image_epc_epc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='rent_frequency',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='backend.property'),
        ),
        migrations.AlterField(
            model_name='propertydata',
            name='property_type',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
