# Generated by Django 4.2.7 on 2023-11-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_prices_id_prices_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationstationdistance',
            name='station_distance_units',
            field=models.DecimalField(decimal_places=16, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
