# Generated by Django 4.2 on 2024-01-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_ownership_rent_frequency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['property_id']},
        ),
        migrations.AlterField(
            model_name='ownership',
            name='shared_ownership',
            field=models.BooleanField(null=True),
        ),
    ]
