# Generated by Django 4.2 on 2024-01-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateagent',
            name='agent_url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='floorplan_url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='propertydata',
            name='property_url',
            field=models.URLField(max_length=300),
        ),
    ]
