# Generated by Django 4.2.7 on 2023-11-19 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_stationstationdistance_station_distance_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorplanProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorplan_url', models.URLField()),
                ('floorplan_caption', models.CharField(max_length=100, null=True)),
                ('floorplan_url_resized', models.URLField(null=True)),
                ('floorplan_scraped', models.BooleanField(default=False)),
                ('floorplan_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floorplan_id', to='backend.floorplans')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.propertyvalue')),
            ],
            options={
                'unique_together': {('property', 'floorplan_id')},
            },
        ),
    ]
