# Generated by Django 4.2 on 2024-01-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_estateagent_agent_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettinginfo',
            name='furnishing_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_qualifier',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydata',
            name='furnished',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_dimension',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='council_tax_band',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
