# Generated by Django 4.2 on 2023-11-19 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_floorplanproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplanproperty',
            name='floorplan_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floorplan_id', to='backend.floorplans'),
        ),
        migrations.AddField(
            model_name='imageproperty',
            name='image_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_id', to='backend.images'),
        ),
        migrations.AlterField(
            model_name='floorplanproperty',
            name='floorplan_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageproperty',
            name='image_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
