# Generated by Django 4.2 on 2023-11-19 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_floorplanproperty_floorplan_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='view_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.propertyvalue'),
        ),
    ]
