# Generated by Django 4.2 on 2024-01-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epc',
            name='epc_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
