# Generated by Django 4.2 on 2023-11-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_views_view_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfeature',
            name='key_feature_id',
            field=models.CharField(max_length=20),
        ),
    ]
