# Generated by Django 4.2 on 2024-02-01 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_ownership_rent_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epc',
            name='ei_url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.property'),
        ),
        migrations.AlterField(
            model_name='propertydata',
            name='property_sub_type',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
