# Generated by Django 4.2 on 2023-11-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_keyfeature_key_feature_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='statuses',
            name='status_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='views',
            name='view_id',
            field=models.CharField(max_length=20),
        ),
    ]
