# Generated by Django 4.2 on 2024-02-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_epc_ei_url_alter_image_property_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfeature',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_features', to='backend.property'),
        ),
    ]
