# Generated by Django 4.2 on 2023-11-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_prices_price_id_alter_rooms_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='backend.propertyvalue'),
        ),
    ]
