# Generated by Django 4.2 on 2024-02-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_keyfeature_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorplans', to='backend.property'),
        ),
        migrations.AlterField(
            model_name='premiumlisting',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_listing_history', to='backend.property'),
        ),
        migrations.AlterField(
            model_name='price',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='backend.property'),
        ),
    ]
