# Generated by Django 4.2 on 2024-02-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_keyfeature_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(height_field='image_height', null=True, upload_to='image/', width_field='image_width'),
        ),
    ]
