# Generated by Django 4.2 on 2023-11-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_rooms_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationstationdistance',
            name='station_distance_units',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
    ]
