# Generated by Django 4.2 on 2023-11-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_stationstationdistance_station_distance_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationstationdistance',
            name='station_distance_units',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
