# Generated by Django 4.2.7 on 2023-11-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_stationstationdistance_station_distance_units'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estateagentaccreditation',
            unique_together={('estate_agent_id', 'accreditation_id')},
        ),
        migrations.AlterUniqueTogether(
            name='stationstationdistance',
            unique_together={('property_id', 'station_id')},
        ),
    ]
