# Generated by Django 4.2 on 2024-02-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_text_description_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_dimension',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
