# Generated by Django 4.2 on 2024-02-21 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_stationdistance_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdistance',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.propertydata'),
        ),
    ]
