# Generated by Django 4.2.7 on 2023-11-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_property_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='epc',
            name='epc_image',
            field=models.ImageField(null=True, upload_to='epc_image/'),
        ),
    ]
