# Generated by Django 4.2 on 2024-02-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_stationdistance_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateagent',
            name='agent_full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
