# Generated by Django 4.2 on 2024-02-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_imagedimensions_propertydata_total_pixels'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagedimensions',
            table='image dimensions',
        ),
    ]
