# Generated by Django 4.2 on 2024-02-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_imagedimensions_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagedimensions',
            table='image_dimensions',
        ),
    ]
