# Generated by Django 4.2 on 2024-02-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_imagedimensions_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedimensions',
            name='avg_image_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imagedimensions',
            name='avg_image_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imagedimensions',
            name='num_images',
            field=models.IntegerField(null=True),
        ),
    ]
