# Generated by Django 4.2 on 2024-02-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_imagedimensions_avg_image_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageDistanceFromStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=15, unique=True)),
                ('avg_distance', models.DecimalField(decimal_places=10, max_digits=50, null=True)),
                ('number_of_stations', models.IntegerField(null=True)),
            ],
        ),
    ]
