# Generated by Django 4.2 on 2024-02-22 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_averagedistancefromstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydata',
            name='avg_station_distance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.averagedistancefromstation'),
        ),
    ]
