# Generated by Django 4.2 on 2024-02-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_propertydata_avg_station_distance'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='averagedistancefromstation',
            table='average_station_distance',
        ),
    ]
