# Generated by Django 4.2 on 2024-02-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_averagedistancefromstation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EverPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=15, unique=True)),
                ('ever_premium', models.DecimalField(decimal_places=10, max_digits=50, null=True)),
                ('ever_featured', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ever_premium',
            },
        ),
        migrations.AlterModelTable(
            name='businesstype',
            table='business_type',
        ),
        migrations.AlterModelTable(
            name='lettinginfo',
            table='letting_info',
        ),
    ]
