# Generated by Django 4.2 on 2024-02-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_everpremium_alter_businesstype_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everpremium',
            name='ever_premium',
            field=models.IntegerField(null=True),
        ),
    ]
