# Generated by Django 4.2 on 2024-02-22 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_alter_everpremium_ever_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydata',
            name='ever_premium',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.everpremium'),
        ),
    ]
