# Generated by Django 4.2 on 2024-02-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_propertydata_ever_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedimensions',
            name='property_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
