# Generated by Django 4.2 on 2024-02-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_alter_imagedimensions_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_file',
        ),
        migrations.AddField(
            model_name='image',
            name='image_binary',
            field=models.BinaryField(null=True),
        ),
    ]
