FROM python:3.10.13

WORKDIR /app

COPY . /app/
COPY .env.dev /app/.env.dev

RUN apt-get update && apt-get install -y \ 
    cron \  
    nano

RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

RUN mkdir /commands \
    && echo '#!/bin/bash' > \
    /commands/run_spiders.sh \
    && echo '/usr/local/bin/python /app/run_spiders.py s; /usr/local/bin/python /app/run_spiders.py p; /usr/local/bin/python /app/run_spiders.py r; /usr/local/bin/python /app/run_spiders.py e; /usr/local/bin/python /app/run_spiders.py i;' >> \
    /commands/run_spiders.sh \ 
    && chmod +x /commands/run_spiders.sh
RUN echo "$(cat /app/.env.dev)" \
    >> /etc/crontab
RUN echo "0 0 * * * root bash -c /commands/run_spiders.sh > /app/cron.log 2>&1" \
    >> /etc/crontab

RUN python manage.py makemigrations
RUN python manage.py migrate

RUN touch /app/cron.log

CMD ["cron", "-f"]